name: "CI Tests"

on:
  - "pull_request"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
        rails-version:
          - "7.2"
          - "8.0"
          - "8.1"

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    name: ${{ format('Tests (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-node@v2"
        with:
          node-version: "14"
      - uses: "ruby/setup-ruby@v1"
        with:
          rubygems: 3.3.13
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bin/rails standard
      - run: yarn install
      - run: yarn build
      - run: bin/rails test:all

      - name: Fail when generated changes are not checked-in
        run: |
          git update-index --refresh
          git diff-index --quiet HEAD --
